# <font face = 'Impact' color = '#FFAEBC' > Loading, Organizing, and Storing Data Two <font/>
#### <font face = 'Times New Roman' color = '#B5E5CF'> License: GPL v3.0<font/>
#### <font face = 'Times New Roman' color = '#B5E5CF'> Author and Trainer: Paolo Hilado MSc. (Data Science)<font/>
In this section, we’ll learn how to load datasets into Python using the pandas library, focusing on common file formats like CSV. Once the data is loaded into a DataFrame, we’ll explore simple techniques to identify missing values. This includes checking for NaN entries, summarizing null counts per column, and using visual or logical methods to detect incomplete rows. Spotting missing data early is an important step in ensuring data quality before analysis or modeling.

In [1]:
# Import the necessary libraries
import pandas as pd
import numpy as np
import os

In [2]:
#Checking out the current working directory
print(os.getcwd())

C:\Users\Sheila Magolama\pythonTraining\day 1 data

In [5]:
#Loading a .Sav file and assigning it to a variable
#We will open and work on "Bank.sav"
df = pd.read_spss("PracticeTest.sav")
df

,Item1,Item2,Item3,Item4,Item5,Item6,Item7,Item8,Item9,Item10,...,Item21,Item22,Item23,Item24,Item25,Item26,Item27,Item28,Item29,Item30
0,1.0,2.0,1.0,5.0,2.0,3.0,1.0,5.0,4.0,1.0,...,4.0,2.0,4.0,3.0,4.0,1.0,2.0,1.0,2.0,4.0
1,5.0,5.0,1.0,4.0,5.0,4.0,5.0,5.0,5.0,5.0,...,5.0,1.0,5.0,3.0,5.0,4.0,3.0,1.0,3.0,3.0
2,2.0,5.0,1.0,3.0,3.0,2.0,5.0,1.0,5.0,2.0,...,2.0,2.0,3.0,4.0,2.0,5.0,3.0,2.0,1.0,2.0
3,2.0,4.0,1.0,5.0,2.0,3.0,2.0,2.0,2.0,5.0,...,2.0,2.0,3.0,4.0,2.0,4.0,5.0,1.0,3.0,2.0
4,4.0,3.0,1.0,5.0,4.0,2.0,5.0,4.0,1.0,1.0,...,5.0,1.0,5.0,3.0,4.0,4.0,2.0,2.0,2.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
454,1.0,4.0,3.0,5.0,2.0,4.0,5.0,2.0,2.0,2.0,...,4.0,1.0,4.0,2.0,3.0,2.0,4.0,4.0,3.0,1.0
455,1.0,4.0,1.0,3.0,3.0,3.0,2.0,5.0,4.0,5.0,...,4.0,4.0,2.0,5.0,3.0,3.0,3.0,2.0,2.0,2.0
456,2.0,5.0,1.0,5.0,1.0,4.0,5.0,5.0,5.0,5.0,...,1.0,1.0,4.0,3.0,1.0,2.0,5.0,1.0,3.0,2.0
457,4.0,4.0,4.0,5.0,2.0,2.0,2.0,2.0,4.0,5.0,...,2.0,1.0,2.0,1.0,3.0,4.0,4.0,3.0,4.0,5.0
458,1.0,5.0,2.0,5.0,2.0,5.0,2.0,2.0,4.0,2.0,...,4.0,2.0,2.0,2.0,3.0,2.0,5.0,4.0,2.0,3.0

In [6]:
# Viewing the first 5 rows
df.head(5)

,Item1,Item2,Item3,Item4,Item5,Item6,Item7,Item8,Item9,Item10,...,Item21,Item22,Item23,Item24,Item25,Item26,Item27,Item28,Item29,Item30
0,1.0,2.0,1.0,5.0,2.0,3.0,1.0,5.0,4.0,1.0,...,4.0,2.0,4.0,3.0,4.0,1.0,2.0,1.0,2.0,4.0
1,5.0,5.0,1.0,4.0,5.0,4.0,5.0,5.0,5.0,5.0,...,5.0,1.0,5.0,3.0,5.0,4.0,3.0,1.0,3.0,3.0
2,2.0,5.0,1.0,3.0,3.0,2.0,5.0,1.0,5.0,2.0,...,2.0,2.0,3.0,4.0,2.0,5.0,3.0,2.0,1.0,2.0
3,2.0,4.0,1.0,5.0,2.0,3.0,2.0,2.0,2.0,5.0,...,2.0,2.0,3.0,4.0,2.0,4.0,5.0,1.0,3.0,2.0
4,4.0,3.0,1.0,5.0,4.0,2.0,5.0,4.0,1.0,1.0,...,5.0,1.0,5.0,3.0,4.0,4.0,2.0,2.0,2.0,3.0

In [7]:
# Viewing the last 5 rows
df.tail(5)

,Item1,Item2,Item3,Item4,Item5,Item6,Item7,Item8,Item9,Item10,...,Item21,Item22,Item23,Item24,Item25,Item26,Item27,Item28,Item29,Item30
454,1.0,4.0,3.0,5.0,2.0,4.0,5.0,2.0,2.0,2.0,...,4.0,1.0,4.0,2.0,3.0,2.0,4.0,4.0,3.0,1.0
455,1.0,4.0,1.0,3.0,3.0,3.0,2.0,5.0,4.0,5.0,...,4.0,4.0,2.0,5.0,3.0,3.0,3.0,2.0,2.0,2.0
456,2.0,5.0,1.0,5.0,1.0,4.0,5.0,5.0,5.0,5.0,...,1.0,1.0,4.0,3.0,1.0,2.0,5.0,1.0,3.0,2.0
457,4.0,4.0,4.0,5.0,2.0,2.0,2.0,2.0,4.0,5.0,...,2.0,1.0,2.0,1.0,3.0,4.0,4.0,3.0,4.0,5.0
458,1.0,5.0,2.0,5.0,2.0,5.0,2.0,2.0,4.0,2.0,...,4.0,2.0,2.0,2.0,3.0,2.0,5.0,4.0,2.0,3.0

In [8]:
#Checking the structure of the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 459 entries, 0 to 458
Data columns (total 30 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Item1   449 non-null    float64
 1   Item2   449 non-null    float64
 2   Item3   449 non-null    float64
 3   Item4   449 non-null    float64
 4   Item5   450 non-null    float64
 5   Item6   446 non-null    float64
 6   Item7   446 non-null    float64
 7   Item8   446 non-null    float64
 8   Item9   447 non-null    float64
 9   Item10  451 non-null    float64
 10  Item11  451 non-null    float64
 11  Item12  451 non-null    float64
 12  Item13  450 non-null    float64
 13  Item14  450 non-null    float64
 14  Item15  450 non-null    float64
 15  Item16  449 non-null    float64
 16  Item17  450 non-null    float64
 17  Item18  450 non-null    float64
 18  Item19  450 non-null    float64
 19  Item20  450 non-null    float64
 20  Item21  450 non-null    float64
 21  Item22  450 non-null    float64
 22  Item23  450 non-null    float64
 23  Item24  451 non-null    float64
 24  Item25  455 non-null    float64
 25  Item26  453 non-null    float64
 26  Item27  452 non-null    float64
 27  Item28  451 non-null    float64
 28  Item29  451 non-null    float64
 29  Item30  451 non-null    float64
dtypes: float64(30)
memory usage: 107.7 KB

In [9]:
#Slicing the dataframe
#Slice column 3 to 5 with all of its observations
sub = df.iloc[:, 2:5]
sub

     Item3  Item4  Item5
0      1.0    5.0    2.0
1      1.0    4.0    5.0
2      1.0    3.0    3.0
3      1.0    5.0    2.0
4      1.0    5.0    4.0
..     ...    ...    ...
454    3.0    5.0    2.0
455    1.0    3.0    3.0
456    1.0    5.0    1.0
457    4.0    5.0    2.0
458    2.0    5.0    2.0

[459 rows x 3 columns]

In [10]:
#Slice the data frame to only include observations index of 15 to 35
sub1 = df.iloc[15:36, :]
sub1

,Item1,Item2,Item3,Item4,Item5,Item6,Item7,Item8,Item9,Item10,...,Item21,Item22,Item23,Item24,Item25,Item26,Item27,Item28,Item29,Item30
15,2.0,2.0,1.0,4.0,2.0,2.0,2.0,5.0,4.0,2.0,...,2.0,4.0,3.0,3.0,2.0,3.0,5.0,2.0,2.0,3.0
16,2.0,4.0,4.0,3.0,3.0,2.0,2.0,4.0,5.0,4.0,...,1.0,3.0,5.0,5.0,3.0,4.0,4.0,4.0,5.0,3.0
17,2.0,5.0,2.0,2.0,2.0,5.0,2.0,1.0,2.0,2.0,...,5.0,4.0,2.0,2.0,2.0,3.0,5.0,4.0,2.0,4.0
18,2.0,4.0,1.0,4.0,3.0,4.0,5.0,1.0,2.0,5.0,...,1.0,2.0,4.0,4.0,2.0,3.0,5.0,2.0,3.0,2.0
19,4.0,2.0,1.0,2.0,3.0,2.0,2.0,1.0,4.0,5.0,...,2.0,3.0,3.0,5.0,2.0,5.0,3.0,3.0,2.0,1.0
20,5.0,3.0,1.0,1.0,3.0,1.0,2.0,5.0,5.0,5.0,...,5.0,1.0,3.0,1.0,3.0,3.0,3.0,2.0,1.0,2.0
21,5.0,1.0,3.0,1.0,5.0,1.0,4.0,2.0,5.0,2.0,...,5.0,5.0,1.0,4.0,2.0,1.0,1.0,5.0,1.0,2.0
22,5.0,4.0,1.0,3.0,2.0,4.0,5.0,5.0,2.0,4.0,...,4.0,1.0,5.0,1.0,3.0,3.0,1.0,1.0,5.0,2.0
23,3.0,4.0,2.0,5.0,2.0,3.0,5.0,4.0,1.0,1.0,...,5.0,1.0,5.0,3.0,3.0,3.0,3.0,1.0,2.0,3.0
24,2.0,3.0,2.0,3.0,1.0,4.0,2.0,2.0,5.0,5.0,...,5.0,4.0,3.0,1.0,1.0,1.0,5.0,4.0,1.0,1.0
25,3.0,2.0,1.0,1.0,1.0,1.0,5.0,5.0,4.0,5.0,...,5.0,1.0,4.0,5.0,2.0,2.0,2.0,1.0,2.0,1.0
26,1.0,3.0,2.0,5.0,1.0,4.0,1.0,4.0,4.0,5.0,...,5.0,3.0,2.0,3.0,2.0,2.0,3.0,2.0,2.0,1.0
27,1.0,2.0,2.0,4.0,3.0,2.0,2.0,4.0,1.0,1.0,...,1.0,2.0,5.0,1.0,3.0,4.0,3.0,1.0,2.0,2.0
28,4.0,4.0,2.0,5.0,2.0,2.0,2.0,5.0,4.0,1.0,...,2.0,2.0,5.0,3.0,2.0,4.0,5.0,2.0,5.0,2.0
29,5.0,2.0,3.0,2.0,4.0,1.0,2.0,2.0,2.0,1.0,...,5.0,2.0,2.0,2.0,2.0,3.0,4.0,5.0,3.0,4.0
30,4.0,2.0,2.0,5.0,5.0,5.0,5.0,2.0,2.0,5.0,...,2.0,2.0,5.0,2.0,5.0,1.0,2.0,4.0,5.0,3.0
31,1.0,3.0,1.0,2.0,3.0,3.0,1.0,4.0,5.0,2.0,...,1.0,1.0,2.0,3.0,3.0,2.0,2.0,3.0,1.0,3.0
32,1.0,2.0,1.0,5.0,1.0,2.0,2.0,4.0,1.0,2.0,...,1.0,1.0,3.0,2.0,2.0,2.0,2.0,2.0,1.0,3.0
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,2.0,2.0,1.0,2.0,2.0,3.0,5.0,4.0,5.0,5.0,...,2.0,1.0,5.0,4.0,2.0,3.0,5.0,1.0,2.0,2.0
35,2.0,3.0,1.0,1.0,4.0,3.0,1.0,5.0,5.0,2.0,...,2.0,1.0,3.0,5.0,5.0,3.0,3.0,4.0,1.0,3.0

In [11]:
#Checking for NAs or missing cases
df.isnull().values.any()

np.True_

In [12]:
#Subset dataframe to include all rows that is made up of all missing cases
missing_df1= df[df.isnull().all(axis=1)] # take a subset to include all rows with missing cases
missing_df2= df[df.isnull().any(axis=1)] # take a subset to include any row with missing cases

In [13]:
missing_df1

,Item1,Item2,Item3,Item4,Item5,Item6,Item7,Item8,Item9,Item10,...,Item21,Item22,Item23,Item24,Item25,Item26,Item27,Item28,Item29,Item30
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
missing_df2

,Item1,Item2,Item3,Item4,Item5,Item6,Item7,Item8,Item9,Item10,...,Item21,Item22,Item23,Item24,Item25,Item26,Item27,Item28,Item29,Item30
11,2.0,4.0,3.0,4.0,4.0,3.0,2.0,1.0,2.0,5.0,...,1.0,2.0,2.0,2.0,3.0,2.0,4.0,3.0,2.0,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.0,4.0,4.0,2.0,2.0,3.0
51,1.0,2.0,3.0,4.0,2.0,4.0,2.0,2.0,1.0,2.0,...,5.0,2.0,4.0,4.0,2.0,NaN,NaN,NaN,NaN,4.0
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,3.0,4.0,2.0,5.0,2.0,5.0,2.0,2.0,5.0,5.0,...,4.0,2.0,4.0,3.0,2.0,3.0,NaN,NaN,NaN,NaN
78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,4.0,3.0,2.0,4.0,2.0,3.0
95,NaN,NaN,NaN,NaN,3.0,4.0,2.0,5.0,5.0,2.0,...,5.0,4.0,2.0,2.0,2.0,1.0,5.0,2.0,3.0,2.0
158,1.0,3.0,1.0,4.0,2.0,3.0,1.0,4.0,1.0,2.0,...,5.0,1.0,4.0,4.0,2.0,NaN,NaN,NaN,NaN,4.0
184,2.0,2.0,3.0,1.0,3.0,NaN,NaN,NaN,NaN,1.0,...,2.0,2.0,2.0,2.0,2.0,1.0,4.0,4.0,3.0,3.0
185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,4.0,1.0,3.0,2.0,5.0
210,3.0,2.0,1.0,5.0,2.0,2.0,1.0,2.0,1.0,2.0,...,5.0,2.0,2.0,2.0,4.0,5.0,3.0,2.0,5.0,3.0
229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.0,3.0,2.0,4.0,2.0,2.0
299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
360,5.0,3.0,2.0,2.0,3.0,NaN,NaN,NaN,NaN,5.0,...,5.0,1.0,3.0,1.0,2.0,3.0,4.0,NaN,NaN,NaN
367,NaN,NaN,NaN,NaN,1.0,2.0,2.0,4.0,5.0,1.0,...,2.0,2.0,2.0,1.0,3.0,1.0,2.0,2.0,2.0,3.0
382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
403,3.0,4.0,2.0,3.0,3.0,NaN,NaN,NaN,NaN,2.0,...,1.0,4.0,2.0,1.0,2.0,1.0,2.0,2.0,3.0,4.0
410,4.0,2.0,2.0,3.0,2.0,2.0,1.0,4.0,4.0,1.0,...,1.0,2.0,3.0,4.0,2.0,4.0,2.0,2.0,4.0,NaN
427,1.0,3.0,3.0,2.0,1.0,NaN,NaN,NaN,NaN,5.0,...,NaN,NaN,NaN,5.0,2.0,1.0,3.0,1.0,5.0,4.0
432,4.0,1.0,1.0,5.0,3.0,2.0,5.0,5.0,1.0,2.0,...,2.0,1.0,4.0,1.0,1.0,3.0,5.0,4.0,4.0,3.0
439,5.0,1.0,4.0,2.0,NaN,NaN,NaN,NaN,2.0,5.0,...,5.0,2.0,4.0,1.0,5.0,1.0,4.0,1.0,2.0,1.0

In [16]:
missing_df1.to_excel("ForMissing.xlsx")

In [17]:
missing_df2.to_csv("ForMissingsome.csv")

In [18]:
#Subset dataframe to include all rows with complete cases
complete_df= df[df.notnull().all(axis=1)]
complete_df.isnull().values.any()

np.False_

In [22]:
complete_df.to_excel("CompleteData.xlsx")

In [19]:
#Getting a simple descriptives for incomplete and complete records
desc1 = df.describe()
desc2 =  complete_df.describe()

In [20]:
desc1.T

        count      mean       std  min  25%  50%  75%  max
Item1   449.0  2.398664  1.347649  1.0  1.0  2.0  3.0  5.0
Item2   449.0  3.044543  1.222108  1.0  2.0  3.0  4.0  5.0
Item3   449.0  1.864143  0.991834  1.0  1.0  2.0  2.0  5.0
Item4   449.0  3.463252  1.357555  1.0  2.0  4.0  5.0  5.0
Item5   450.0  2.475556  1.016820  1.0  2.0  2.0  3.0  5.0
Item6   446.0  3.152466  1.289223  1.0  2.0  3.0  4.0  5.0
Item7   446.0  2.896861  1.551553  1.0  2.0  2.0  5.0  5.0
Item8   446.0  3.125561  1.545540  1.0  2.0  4.0  5.0  5.0
Item9   447.0  3.111857  1.573610  1.0  2.0  4.0  5.0  5.0
Item10  451.0  3.015521  1.653879  1.0  2.0  2.0  5.0  5.0
Item11  451.0  2.880266  1.581514  1.0  2.0  2.0  5.0  5.0
Item12  451.0  3.716186  1.525831  1.0  2.0  4.0  5.0  5.0
Item13  450.0  3.782222  1.555691  1.0  2.0  5.0  5.0  5.0
Item14  450.0  2.997778  1.574432  1.0  2.0  2.0  5.0  5.0
Item15  450.0  2.786667  1.633120  1.0  1.0  2.0  5.0  5.0
Item16  449.0  2.530067  1.558276  1.0  1.0  2.0  4.0  5.0
Item17  450.0  2.940000  1.564771  1.0  2.0  2.0  5.0  5.0
Item18  450.0  3.537778  1.565111  1.0  2.0  4.0  5.0  5.0
Item19  450.0  3.226667  1.631319  1.0  2.0  4.0  5.0  5.0
Item20  450.0  2.873333  1.656317  1.0  2.0  2.0  5.0  5.0
Item21  450.0  3.300000  1.600738  1.0  2.0  4.0  5.0  5.0
Item22  450.0  1.975556  1.056037  1.0  1.0  2.0  2.0  5.0
Item23  450.0  3.342222  1.327538  1.0  2.0  3.0  5.0  5.0
Item24  451.0  2.955654  1.286782  1.0  2.0  3.0  4.0  5.0
Item25  455.0  2.657143  1.122962  1.0  2.0  3.0  3.0  5.0
Item26  453.0  2.688742  1.174124  1.0  2.0  3.0  3.0  5.0
Item27  452.0  3.595133  1.243082  1.0  3.0  4.0  5.0  5.0
Item28  451.0  2.235033  1.134398  1.0  1.0  2.0  3.0  5.0
Item29  451.0  2.445676  1.161818  1.0  2.0  2.0  3.0  5.0
Item30  451.0  2.312639  1.075916  1.0  1.0  2.0  3.0  5.0

In [21]:
desc2.T

        count      mean       std  min  25%  50%  75%  max
Item1   437.0  2.386728  1.344069  1.0  1.0  2.0  3.0  5.0
Item2   437.0  3.057208  1.224342  1.0  2.0  3.0  4.0  5.0
Item3   437.0  1.853547  0.991509  1.0  1.0  2.0  2.0  5.0
Item4   437.0  3.466819  1.358602  1.0  2.0  4.0  5.0  5.0
Item5   437.0  2.478261  1.021605  1.0  2.0  2.0  3.0  5.0
Item6   437.0  3.155606  1.293437  1.0  2.0  3.0  4.0  5.0
Item7   437.0  2.915332  1.553235  1.0  2.0  2.0  5.0  5.0
Item8   437.0  3.123570  1.548399  1.0  2.0  4.0  5.0  5.0
Item9   437.0  3.121281  1.568448  1.0  2.0  4.0  5.0  5.0
Item10  437.0  3.020595  1.654029  1.0  2.0  2.0  5.0  5.0
Item11  437.0  2.894737  1.580528  1.0  2.0  2.0  5.0  5.0
Item12  437.0  3.734554  1.527431  1.0  2.0  4.0  5.0  5.0
Item13  437.0  3.821510  1.541533  1.0  2.0  5.0  5.0  5.0
Item14  437.0  2.990847  1.575299  1.0  2.0  2.0  5.0  5.0
Item15  437.0  2.800915  1.629487  1.0  1.0  2.0  5.0  5.0
Item16  437.0  2.508009  1.557184  1.0  1.0  2.0  4.0  5.0
Item17  437.0  2.922197  1.560224  1.0  2.0  2.0  5.0  5.0
Item18  437.0  3.530892  1.568638  1.0  2.0  4.0  5.0  5.0
Item19  437.0  3.237986  1.630592  1.0  2.0  4.0  5.0  5.0
Item20  437.0  2.890160  1.656740  1.0  2.0  2.0  5.0  5.0
Item21  437.0  3.299771  1.596822  1.0  2.0  4.0  5.0  5.0
Item22  437.0  1.972540  1.059763  1.0  1.0  2.0  2.0  5.0
Item23  437.0  3.354691  1.335835  1.0  2.0  3.0  5.0  5.0
Item24  437.0  2.974828  1.280341  1.0  2.0  3.0  4.0  5.0
Item25  437.0  2.663616  1.126771  1.0  2.0  3.0  3.0  5.0
Item26  437.0  2.695652  1.167725  1.0  2.0  3.0  3.0  5.0
Item27  437.0  3.610984  1.241362  1.0  3.0  4.0  5.0  5.0
Item28  437.0  2.224256  1.135360  1.0  1.0  2.0  3.0  5.0
Item29  437.0  2.430206  1.160435  1.0  2.0  2.0  3.0  5.0
Item30  437.0  2.286041  1.067928  1.0  1.0  2.0  3.0  5.0